version: "3.0"

services:

  nginx-fpm:
    build: .
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html

  wordpress:
    image: wordpress:5.7.2-php7.4-fpm
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${USER_DB:-wordpress}
      WORDPRESS_DB_PASSWORD: ${USER_DB_PASSWORD?Missing MariaDB user password}
      WORDPRESS_DB_NAME: wpdb

  db:
    image: mariadb:10.6.3-focal
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_DB_PASSWORD?Missing MariaDB root password}
      MARIADB_DATABASE: wpdb
      MARIADB_USER: ${USER_DB:-wordpress}
      MARIADB_PASSWORD: ${USER_DB_PASSWORD?Missing MariaDB user password}

volumes:
  wordpress:
  mariadb:
